/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uts_sem3r;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableColumnModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author x260
 */
public class AdminUser extends javax.swing.JFrame {

    /**
     * Creates new form Home_GUI_prodak_router
     */
    private javax.swing.JPanel Canva;
    koneksi cont;
    isertData tambah;
    delate hapus;
    Update rubah;

    public AdminUser() {
        initComponents();
        cont = new koneksi();
        cont.koneksi();
        setResizable(false);
        this.setLocationRelativeTo(this);
        tambah = new isertData();
        hapus = new delate();
        rubah = new Update();

        reftabelProduk();
        refTabelTransaksi();
        
        codeProduk.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                char c = evt.getKeyChar();
                if (!Character.isDigit(c)) {
                    evt.consume();// PERINTAH UNTUK TEXT FIELD AGAR HURUF TIDAK MASUK
                }
            }
        });
        hargaProduk.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                char c = evt.getKeyChar();
                if (!Character.isDigit(c)) {
                    evt.consume();// PERINTAH UNTUK TEXT FIELD AGAR HURUF TIDAK MASUK
                }
            }
        });
        stokProduk.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                char c = evt.getKeyChar();
                if (!Character.isDigit(c)) {
                    evt.consume();// PERINTAH UNTUK TEXT FIELD AGAR HURUF TIDAK MASUK
                }
            }
        });
        editKodeProduk.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                char c = evt.getKeyChar();
                if (!Character.isDigit(c)) {
                    evt.consume();// PERINTAH UNTUK TEXT FIELD AGAR HURUF TIDAK MASUK
                }
            }
        });
        editHarga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                char c = evt.getKeyChar();
                if (!Character.isDigit(c)) {
                    evt.consume();// PERINTAH UNTUK TEXT FIELD AGAR HURUF TIDAK MASUK
                }
            }
        });
        editStok.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                char c = evt.getKeyChar();
                if (!Character.isDigit(c)) {
                    evt.consume();// PERINTAH UNTUK TEXT FIELD AGAR HURUF TIDAK MASUK
                }
            }
        });

    }

    private void reftabelProduk() {
        try {
            String sql = "SELECT "
                    + "id AS 'ID', "
                    + "produkbarang AS 'Produk Barang', "
                    + "stok AS 'Stok', "
                    + "harga AS 'Harga' "
                    + "FROM produktoko";   // ganti dengan nama tabel Anda

            PreparedStatement pst = cont.con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            readTabel.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    private void refTabelTransaksi() {
        try {
            String sql = "SELECT "
                    + "p.produkbarang AS 'Nama Produk', "
                    + "t.jumlah AS 'Jumlah Produk', "
                    + "t.totalharga AS 'Total Harga', "
                    + "t.tanggal AS 'Tanggal' "
                    + "FROM transaksi t "
                    + "JOIN produktoko p ON t.id_produk = p.id "
                    + "ORDER BY t.tanggal DESC";

            PreparedStatement pst = cont.con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();

            Transaksi.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roouterAdah = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        stokProduk = new javax.swing.JTextField();
        namaProduk = new javax.swing.JTextField();
        hargaProduk = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel19 = new javax.swing.JLabel();
        codeProduk = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        editStok = new javax.swing.JTextField();
        editNamaProduk = new javax.swing.JTextField();
        editHarga = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        editKodeProduk = new javax.swing.JTextField();
        UPDATE = new javax.swing.JToggleButton();
        hapusDat = new javax.swing.JToggleButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        readTabel = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        Transaksi = new javax.swing.JTable();
        jLabel23 = new javax.swing.JLabel();
        Hapus = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        roouterAdah.setBackground(new java.awt.Color(255, 255, 255));
        roouterAdah.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Insert Produk"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("Stok Produk");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel5.setText("Nama Produk");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel6.setText("Harga  Produk");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));
        jPanel2.add(stokProduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 180, -1));
        jPanel2.add(namaProduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 180, -1));
        jPanel2.add(hargaProduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 180, -1));

        jLabel7.setText(":");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, -1, -1));

        jLabel8.setText(":");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, -1, -1));

        jLabel9.setText(":");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, -1, -1));

        jToggleButton1.setText("SIMPAN");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 180, -1));

        jLabel19.setText(":");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, -1));
        jPanel2.add(codeProduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 180, -1));

        jLabel24.setText("Kode Produk");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        roouterAdah.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 320, 190));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Update Produk"));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setText("Stok Produk");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel11.setText("Nama Produk");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel12.setText("Harga  Produk");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        editStok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editStokActionPerformed(evt);
            }
        });
        jPanel4.add(editStok, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 180, -1));
        jPanel4.add(editNamaProduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 180, -1));

        editHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editHargaActionPerformed(evt);
            }
        });
        jPanel4.add(editHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 180, -1));

        jLabel13.setText(":");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, -1, -1));

        jLabel14.setText(":");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, -1, -1));

        jLabel15.setText(":");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, -1, -1));

        jLabel21.setText("Kode Produk");
        jPanel4.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel22.setText(":");
        jPanel4.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, -1));
        jPanel4.add(editKodeProduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 180, -1));

        UPDATE.setText("UPDATE");
        UPDATE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UPDATEActionPerformed(evt);
            }
        });
        jPanel4.add(UPDATE, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 130, -1));

        hapusDat.setText("DELATE");
        hapusDat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusDatActionPerformed(evt);
            }
        });
        jPanel4.add(hapusDat, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 140, -1));

        roouterAdah.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 320, 190));

        readTabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nama Produk", "Stok Produk", "Harga Produk"
            }
        ));
        readTabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                readTabelMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(readTabel);

        roouterAdah.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 650, 100));

        Transaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nama Produk", "Jumlah Produk", "Total harga", "Tanggal"
            }
        ));
        Transaksi.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                TransaksiAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(Transaksi);

        roouterAdah.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 500, 120));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel23.setText("Tabel Transaksi");
        roouterAdah.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        Hapus.setText("HAPUS");
        Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusActionPerformed(evt);
            }
        });
        roouterAdah.add(Hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 410, 120, -1));

        jPanel1.setBackground(new java.awt.Color(1, 141, 203));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ikon/menu.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ikon/monggala.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ikon/desa.png"))); // NOI18N
        jLabel3.setText("jLabel3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        jPanel3.setBackground(new java.awt.Color(1, 141, 203));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton5.setText("ADMIN");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 38, Short.MAX_VALUE)
                        .addComponent(jLabel20)
                        .addGap(126, 126, 126)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(157, 157, 157))
        );

        jMenu1.setText("Menu");

        jMenuItem1.setText("Profil");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Keluar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(roouterAdah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(roouterAdah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Mohon Maaf Fitur Ini Masih Belum Tersedia !!!");
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Home_GUI_prodak_leptop2 dasb = new Home_GUI_prodak_leptop2();
        dasb.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        if (namaProduk.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nama Produk belum diisi!");
            return;
        }
        String ProdaukName = namaProduk.getText().trim();

        int kode;
        try {
            kode = Integer.parseInt(codeProduk.getText().trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Kode Produk belum diisi!");
            return;
        }

        int stok;
        try {
            stok = Integer.parseInt(stokProduk.getText().trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Stok Produk belum diisi!");
            return;
        }

        long harga;
        try {
            harga = Long.parseLong(hargaProduk.getText().trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Harga Produk belum diisi!");
            return;
        }
        System.out.println(ProdaukName + kode + stok + harga);
        tambah.insertProduk(kode, ProdaukName, stok, harga);
        reftabelProduk();

    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void readTabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_readTabelMouseClicked
        // TODO add your handling code here:
        int row = readTabel.getSelectedRow();
        if (row == -1) {
            return;
        }
        String ID = readTabel.getValueAt(row, 0).toString();
        String ProdukBarang = readTabel.getValueAt(row, 1).toString();
        String Stok = readTabel.getValueAt(row, 2).toString();
        String Harga = readTabel.getValueAt(row, 3).toString();

        editKodeProduk.setText(ID);
        editNamaProduk.setText(ProdukBarang);

        editHarga.setText(Stok);
        editStok.setText(Harga);
    }//GEN-LAST:event_readTabelMouseClicked

    private void editHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editHargaActionPerformed

    private void editStokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editStokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editStokActionPerformed

    private void hapusDatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusDatActionPerformed
        // TODO add your handling code here:
        int kode;
        try {
            kode = Integer.parseInt(editKodeProduk.getText().trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Kode Produk belum diisi!");
            return;
        }
        hapus.deleteData(kode);
        reftabelProduk();
    }//GEN-LAST:event_hapusDatActionPerformed

    private void UPDATEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UPDATEActionPerformed
        // TODO add your handling code here:
        if (editNamaProduk.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nama Produk belum diisi!");
            return;
        }
        String ProdaukName = editNamaProduk.getText().trim();

        int kode;
        try {
            kode = Integer.parseInt(editKodeProduk.getText().trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Kode Produk belum diisi!");
            return;
        }

        int stok;
        try {
            stok = Integer.parseInt(editStok.getText().trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Stok Produk belum diisi!");
            return;
        }

        long harga;
        try {
            harga = Long.parseLong(editHarga.getText().trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Harga Produk belum diisi!");
            return;
        }

        rubah.updateProduk(kode, ProdaukName, stok, harga);
        reftabelProduk();
    }//GEN-LAST:event_UPDATEActionPerformed

    private void TransaksiAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_TransaksiAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_TransaksiAncestorAdded

    private void HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusActionPerformed
        // TODO add your handling code here:
        hapus.hapusSemua();
        refTabelTransaksi();
    }//GEN-LAST:event_HapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton Hapus;
    private javax.swing.JTable Transaksi;
    private javax.swing.JToggleButton UPDATE;
    private javax.swing.JTextField codeProduk;
    private javax.swing.JTextField editHarga;
    private javax.swing.JTextField editKodeProduk;
    private javax.swing.JTextField editNamaProduk;
    private javax.swing.JTextField editStok;
    private javax.swing.JToggleButton hapusDat;
    private javax.swing.JTextField hargaProduk;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField namaProduk;
    private javax.swing.JTable readTabel;
    private javax.swing.JPanel roouterAdah;
    private javax.swing.JTextField stokProduk;
    // End of variables declaration//GEN-END:variables
}
