/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PERTEMUAN_09;

import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author x260
 */
public class dataMahasiswa extends javax.swing.JFrame {

    /**
     * Creates new form dataMahasiswa
     */
    private MahasiswaService runFunction;
    private ButtonGroup bgJenisKelamin;
    private ButtonGroup bgJenisKelaminEdit;

    public dataMahasiswa() {
        initComponents();

        bgJenisKelamin = new ButtonGroup();

        bgJenisKelamin.add(rbLaki);
        bgJenisKelamin.add(rbPerempuan);

        bgJenisKelaminEdit = new ButtonGroup();

        bgJenisKelaminEdit.add(rbLakiEdit);
        bgJenisKelaminEdit.add(rbPerempuanEdit);

        rbLaki.setActionCommand("L");
        rbPerempuan.setActionCommand("P");

        rbLakiEdit.setActionCommand("L");
        rbPerempuanEdit.setActionCommand("P");

        DefaultTableCellRenderer headerRenderer
                = (DefaultTableCellRenderer) outTable.getTableHeader().getDefaultRenderer();
        headerRenderer.setHorizontalAlignment(SwingConstants.CENTER);
        setLocationRelativeTo(null);
        setResizable(false);
        runFunction = new ImplemensFuntion();

        nimIn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                char c = evt.getKeyChar();
                if (!Character.isDigit(c)) {
                    evt.consume();// PERINTAH UNTUK TEXT FIELD AGAR HURUF TIDAK MASUK
                }
            }
        });

        loadTable();
    }

    private void loadTable() {
        DefaultTableModel model = (DefaultTableModel) outTable.getModel();
        model.setRowCount(0); // bersihkan tabel

        for (Object[] row : runFunction.getAll()) {
            model.addRow(row);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        content = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        containerInput = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        namaIn = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        rbPerempuan = new javax.swing.JRadioButton();
        rbLaki = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        nimIn = new javax.swing.JTextField();
        save = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        alamatIn1 = new javax.swing.JTextArea();
        containerOutput = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        outTable = new javax.swing.JTable();
        containerEdit = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        rbLakiEdit = new javax.swing.JRadioButton();
        rbPerempuanEdit = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        nimEdit = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        namaEdit = new javax.swing.JTextField();
        remove = new javax.swing.JButton();
        saveEdit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        alamatEdit = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        content.setBackground(new java.awt.Color(255, 255, 255));
        content.setPreferredSize(new java.awt.Dimension(1050, 541));
        content.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("DATA MAHASISWA ILKOM UNU BLITAR 2026 ");
        content.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, -1, -1));

        containerInput.setBackground(new java.awt.Color(255, 255, 255));
        containerInput.setBorder(javax.swing.BorderFactory.createTitledBorder("INPUT DATA MAHASISWA"));
        containerInput.setToolTipText("");
        containerInput.setPreferredSize(new java.awt.Dimension(547, 220));
        containerInput.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        containerInput.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 27, -1, -1));

        jLabel4.setText("JENIS KELAMIN");
        jLabel4.setPreferredSize(new java.awt.Dimension(93, 23));
        containerInput.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 80, -1));

        jLabel6.setText("NAMA");
        jLabel6.setPreferredSize(new java.awt.Dimension(60, 20));
        containerInput.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 40, -1));
        containerInput.add(namaIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 430, -1));

        jLabel7.setText(":");
        jLabel7.setPreferredSize(new java.awt.Dimension(60, 20));
        containerInput.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 10, -1));

        jLabel8.setText(":");
        jLabel8.setPreferredSize(new java.awt.Dimension(60, 20));
        containerInput.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 10, -1));

        jLabel9.setText(":");
        jLabel9.setPreferredSize(new java.awt.Dimension(60, 20));
        containerInput.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 10, -1));

        jLabel10.setText("ALAMAT");
        jLabel10.setPreferredSize(new java.awt.Dimension(60, 20));
        containerInput.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 40, -1));

        rbPerempuan.setBackground(new java.awt.Color(255, 255, 255));
        rbPerempuan.setText("Perempuan");
        containerInput.add(rbPerempuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, -1, -1));

        rbLaki.setBackground(new java.awt.Color(255, 255, 255));
        rbLaki.setText("Laki Laki");
        containerInput.add(rbLaki, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, -1, -1));

        jLabel11.setText("NIM");
        jLabel11.setPreferredSize(new java.awt.Dimension(60, 20));
        containerInput.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 40, -1));

        nimIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nimInActionPerformed(evt);
            }
        });
        containerInput.add(nimIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 430, -1));

        save.setText("SIMPAN DATA ");
        save.setPreferredSize(new java.awt.Dimension(79, 23));
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        containerInput.add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 240, -1));

        jScrollPane3.setAutoscrolls(true);

        alamatIn1.setColumns(20);
        alamatIn1.setRows(5);
        alamatIn1.setAutoscrolls(false);
        jScrollPane3.setViewportView(alamatIn1);

        containerInput.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 430, 80));

        content.add(containerInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 530, 230));

        containerOutput.setBackground(new java.awt.Color(255, 255, 255));
        containerOutput.setBorder(javax.swing.BorderFactory.createTitledBorder("OUTPUT  DATA MAHASISWA"));
        containerOutput.setToolTipText("");
        containerOutput.setPreferredSize(new java.awt.Dimension(547, 220));
        containerOutput.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        containerOutput.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 27, -1, -1));

        outTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NIM", "NAMA", "ALAMAT", "JENIS KELAMIIN"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(outTable);

        containerOutput.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 510, 200));

        content.add(containerOutput, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 530, 230));

        containerEdit.setBackground(new java.awt.Color(255, 255, 255));
        containerEdit.setBorder(javax.swing.BorderFactory.createTitledBorder("EDIIT DATA"));
        containerEdit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setText("ALAMAT BARU ");
        jLabel5.setPreferredSize(new java.awt.Dimension(60, 20));
        containerEdit.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 80, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Masukkan NIM  yang akan diubah atau dihapus");
        jLabel12.setPreferredSize(new java.awt.Dimension(60, 20));
        containerEdit.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 280, -1));

        jLabel13.setText("NAMA BARU");
        jLabel13.setPreferredSize(new java.awt.Dimension(60, 20));
        containerEdit.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 60, -1));

        rbLakiEdit.setBackground(new java.awt.Color(255, 255, 255));
        rbLakiEdit.setText("Laki Laki");
        containerEdit.add(rbLakiEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, -1));

        rbPerempuanEdit.setBackground(new java.awt.Color(255, 255, 255));
        rbPerempuanEdit.setText("Perempuan");
        containerEdit.add(rbPerempuanEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, -1, -1));

        jLabel14.setText("JENIS KELAMIN");
        jLabel14.setPreferredSize(new java.awt.Dimension(93, 23));
        containerEdit.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 80, -1));

        nimEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nimEditActionPerformed(evt);
            }
        });
        containerEdit.add(nimEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 450, -1));

        jLabel15.setText(":");
        jLabel15.setPreferredSize(new java.awt.Dimension(60, 20));
        containerEdit.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 10, -1));

        jLabel16.setText(":");
        jLabel16.setPreferredSize(new java.awt.Dimension(60, 20));
        containerEdit.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 10, -1));

        namaEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaEditActionPerformed(evt);
            }
        });
        containerEdit.add(namaEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 350, -1));

        remove.setText("HAPUS DATA");
        remove.setPreferredSize(new java.awt.Dimension(79, 23));
        remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeActionPerformed(evt);
            }
        });
        containerEdit.add(remove, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 220, -1));

        saveEdit.setText("SIMPAN DATA PERUBAHAN");
        saveEdit.setPreferredSize(new java.awt.Dimension(79, 23));
        saveEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveEditActionPerformed(evt);
            }
        });
        containerEdit.add(saveEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 220, -1));

        jScrollPane1.setAutoscrolls(true);

        alamatEdit.setColumns(20);
        alamatEdit.setRows(5);
        alamatEdit.setAutoscrolls(false);
        jScrollPane1.setViewportView(alamatEdit);

        containerEdit.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 350, 60));

        content.add(containerEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 60, 470, 260));

        getContentPane().add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setBounds(0, 0, 1050, 571);
    }// </editor-fold>//GEN-END:initComponents

    private void removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeActionPerformed
        // TODO add your handling code here:
        if (nimEdit.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "NIM wajib di isi !!!");
            nimIn.requestFocus();
            return;
        }
        long nimConvert = Long.parseLong(nimEdit.getText().trim());
        runFunction.delete(nimConvert);
        loadTable();

    }//GEN-LAST:event_removeActionPerformed

    private void nimInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nimInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nimInActionPerformed

    private void nimEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nimEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nimEditActionPerformed

    private void namaEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaEditActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        if (nimIn.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "NIM wajib di isi !!!");
            nimIn.requestFocus();
            return;
        } else if (namaIn.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "NAMA wajib di isi !!!");
            nimIn.requestFocus();
            return;
        } else if (alamatIn1.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "ALAMAT wajib di isi !!!");
            nimIn.requestFocus();
            return;
        } else if (bgJenisKelamin.getSelection() == null) {
            JOptionPane.showMessageDialog(this, "Pilih jenis kelamin terlebih dahulu !!!");
            return;
        }

        long nimConvert = Long.parseLong(nimIn.getText().trim());
        System.out.println(nimConvert);
        System.out.println(namaIn.getText().trim());
        System.out.println(alamatIn1.getText().trim());
        System.out.println(bgJenisKelamin.getSelection().getActionCommand());

        runFunction.insert(nimConvert, namaIn.getText(), alamatIn1.getText(), bgJenisKelamin.getSelection().getActionCommand());
        loadTable();
    }//GEN-LAST:event_saveActionPerformed

    private void saveEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveEditActionPerformed
        // TODO add your handling code here:
        if (nimEdit.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "NIM wajib di isi !!!");
            nimEdit.requestFocus();
            return;
        } else if (namaEdit.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "NAMA wajib di isi !!!");
            namaEdit.requestFocus();
            return;
        } else if (alamatEdit.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "ALAMAT wajib di isi !!!");
            alamatEdit.requestFocus();
            return;
        } else if (bgJenisKelaminEdit.getSelection() == null) {
            JOptionPane.showMessageDialog(this, "Pilih jenis kelamin terlebih dahulu !!!");
            return;
        }

        long nimConvert = Long.parseLong(nimEdit.getText().trim());
        runFunction.update(nimConvert, namaEdit.getText(), alamatEdit.getText(), bgJenisKelaminEdit.getSelection().getActionCommand());
        loadTable();
    }//GEN-LAST:event_saveEditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dataMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dataMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dataMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dataMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dataMahasiswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea alamatEdit;
    private javax.swing.JTextArea alamatIn1;
    private javax.swing.JPanel containerEdit;
    private javax.swing.JPanel containerInput;
    private javax.swing.JPanel containerOutput;
    private javax.swing.JPanel content;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField namaEdit;
    private javax.swing.JTextField namaIn;
    private javax.swing.JTextField nimEdit;
    private javax.swing.JTextField nimIn;
    private javax.swing.JTable outTable;
    private javax.swing.JRadioButton rbLaki;
    private javax.swing.JRadioButton rbLakiEdit;
    private javax.swing.JRadioButton rbPerempuan;
    private javax.swing.JRadioButton rbPerempuanEdit;
    private javax.swing.JButton remove;
    private javax.swing.JButton save;
    private javax.swing.JButton saveEdit;
    // End of variables declaration//GEN-END:variables
}
